###
GET http://localhost:3000/things.json



###
POST http://localhost:3000/things.json

###
POST http://localhost:3000/things.json
Content-Type: application/json

{
  "name": "Selfie Toaster",
  "prices": "75",
  "image_url": "https://im.indiatimes.in/media/content/2018/Jun/weirdest_technology_1528369463_725x725.jpg",
  "description": "Self-obsession just got foody. You’ve put your selfies on Instagram, you’ve saved it as your wallpaper. You’ve even laminated it on your cups. Where do you take it next? That’s right, you take it to your plates. Mail your selfie to Vermont Novelty Toaster Corp, the creators of Selfie Toaster, and they would make a metal plate with the impression. Put in your toaster and you have your face on your toast. A morning of Me, Myself and I."
}

###
PATCH http://localhost:3000/home/8.json
Content-Type: application/json

{
  "name": "Lightsaber"
}

###
DELETE http://localhost:3000/things/5.json